### PR TITLE
Rush3 dev experimental

### PR DESCRIPTION
**Pull request by floordiv**
Made a bit less async, but increased performance for a lot. Now using less glamorous but more fast variant with usual attributes. So it isn't so beauty as it was, but on my machine performance increased for 50k RPS. Also added `ctx` field to Request method that is used only by middlewares and handlers. Also did smth else, but don't remember what did I actually do as it was a long time ago

### CODE REVIEW

**Comment by floordiv** [comment]
Brilliant pull request. Thank you a lot, my friend. You're my the best contributor ever.

**Comment by krau5** [comment]
нркмн

**Comment by floordiv** [comment]
> нркмн

развелось тут...

English, please. I can't understand you

**Comment by krau5** [comment]
nrkmn

**Pull request merged**
